### PR TITLE
Add gawk 3.1.6.

### PR DESCRIPTION
**Pull request by bsmiles32**
which is now needed to build mupen64plus-core.

### CODE REVIEW

**Comment by bsmiles32** [comment]
This should help writing adequate msvc file for mupen64plus-core PR 213.

**Comment by richard42** [comment]
Is this still required?  There was a lot of back-and-forth with the PR #213.

**Comment by bsmiles32** [comment]
Yes for visual studio builds

**Comment by richard42** [comment]
it looks like this is in the root of the repository.  Can you move it to the win32deps repository instead of mupen64plus-core?  I'd rather not have it here for the linux/macos users.

**Comment by bsmiles32** [comment]
I don't see what's wrong with this PR. Gawk is added in a subfolder the mupen64plus-win32deps repo. ?

**Comment by richard42** [comment]
oh I'm sorry, for some reason I thought this was a PR on the core repo

**Pull request merged**
